plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-2.4.2.cjs

packageExtensions:
  # TODO: remove when new version is released https://github.com/fastify/fast-json-stringify/pull/315
  fast-json-stringify@*:
    dependencies: 
      long: "*"

  # I don't want to add pg-native to my package.json 
  slonik@*:
    dependencies: 
      pg-native: "*"