CREATE EXTENSION moddatetime;

-- public.game_states definition

-- Drop table

-- DROP TABLE public.game_states;

CREATE TABLE public.game_states (
                                    id int2 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                    state varchar NOT NULL,
                                    CONSTRAINT game_state_pkey PRIMARY KEY (id)
);


-- public.winners definition

-- Drop table

-- DROP TABLE public.winners;

CREATE TABLE public.winners (
                                id int2 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                winner varchar NOT NULL,
                                CONSTRAINT winner_pkey PRIMARY KEY (id)
);


-- public.games definition

-- Drop table

-- DROP TABLE public.games;

CREATE TABLE public.games (
                              id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                              short_id varchar(6) NOT NULL,
                              player_one_id uuid NOT NULL,
                              player_two_id uuid NOT NULL,
                              fk_game_state_id int2 NOT NULL,
                              fk_winner_id int2 NULL,
                              created_on timestamptz NOT NULL DEFAULT now(),
                              updated_on timestamptz NOT NULL DEFAULT now(),
                              CONSTRAINT game_pkey PRIMARY KEY (id),
                              CONSTRAINT game_game_state_id_fkey FOREIGN KEY (fk_game_state_id) REFERENCES public.game_states(id),
                              CONSTRAINT game_winner_fkey FOREIGN KEY (fk_winner_id) REFERENCES public.winners(id)
);
CREATE UNIQUE INDEX game_short_id_uindex ON public.games USING btree (short_id);

CREATE TRIGGER mdt_games
    BEFORE UPDATE ON games
    FOR EACH ROW
EXECUTE PROCEDURE moddatetime (updated_on);

-- public.moves definition

-- Drop table

-- DROP TABLE public.moves;

CREATE TABLE public.moves (
                              id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                              board_x int2 NOT NULL,
                              board_y int2 NOT NULL,
                              tile_x int2 NOT NULL,
                              tile_y int2 NOT NULL,
                              fk_game_short_id varchar(6) NOT NULL,
                              created_on timestamptz NOT NULL DEFAULT now(),
                              CONSTRAINT move_pkey PRIMARY KEY (id),
                              CONSTRAINT move_fk_game_short_id_fkey FOREIGN KEY (fk_game_short_id) REFERENCES public.games(short_id)
);


-- Insert Data

INSERT INTO public.winners (winner) VALUES
('Cross'),
('Circle');

INSERT INTO public.game_states (state) VALUES
('Created'),
('InProgress'),
('Finished');
